database:
  url: postgres://demouser:secret@localhost:5432/demo?application_name=user-service

kafka:
  broker:
    urls: localhost:9092
  schema_registry:
    url: http://localhost:8081
  topic:
    mappings:
      - id: user
        topic_name: user
        partitions: 2

security:
  jwks:
    issuer: http://localhost:8080/realms/app
    url: http://localhost:8080/realms/app/protocol/openid-connect/certs