[workspace]

members = [
    "app-accommodation-service",
    "app-kafka-connector-relationaldb",
    "common-db",
    "common-db-mongodb",
    "common-error",
    "common-kafka",
    "common-tracing",
    "kafka-connector-mongodb",
    "kafka-schema-accommodation",
    "kafka-schema-common",
    "kafka-schema-publisher",
    "kafka-schema-user",
    "kafka-topic-client",
    "opentelemetry-propagator-b3",
    "user-service"
]
