[workspace]

members = [
    "common-db",
    "common-error",
    "kafka-common",
    "kafka-connector",
    "kafka-schema-common",
    "kafka-schema-publisher",
    "kafka-schema-user",
    "kafka-topic-client",
    "opentelemetry-propagator-b3",
    "tracing-common",
    "user-service"
]
