#fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Vertical"
indent_style = "Block"
imports_granularity = "Item"
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
where_single_line = true
wrap_comments = true