federation_version: 2
subgraphs:
  accommodations:
    routing_url: http://localhost:3005/graphql
    schema:
      subgraph_url: http://localhost:3005/graphql
  users:
    routing_url: http://localhost:3000/graphql
    schema:
      subgraph_url: http://localhost:3000/graphql