database:
  url: mongodb://localhost:27017/accommodation-service?replicaSet=replica-set-1

kafka:
  broker:
    urls: localhost:9092
  schema_registry:
    url: http://localhost:8081
  topic:
    mappings:
      - id: accommodation
        topic_name: accommodation
        partitions: 2

security:
  jwks:
    issuer: http://localhost:8080/realms/app
    url: http://localhost:8080/realms/app/protocol/openid-connect/certs