database:
  connection:
    pool:
      min: 1
      max: 2
    #Optional parameters
    idle_timeout: 30
    # connect_timeout:
    # max_lifetime:
  logging:
    enabled: false

logging:
  level:
    root: warn
    directives:
      - namespace: app_kafka_connector_relationaldb
        level: debug
      - namespace: app_kafka_connector_relationaldb::event
        level: trace
      - namespace: common_error
        level: trace
      - namespace: tower_http
        level: debug
      - namespace: sea_orm::database::transaction
        level: info
      - namespace: sqlx::query
        level: info

server:
  port: 3001